"""add_nationality_remove_field_of_study

Revision ID: e6a099b034df
Revises: 02cf5b9a7e1e
Create Date: 2025-12-29 16:43:06.208365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a099b034df'
down_revision: Union[str, None] = '02cf5b9a7e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nationality', sa.Text(), nullable=True))
    op.drop_column('users', 'field_of_study')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('field_of_study', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'nationality')
    # ### end Alembic commands ###
